### ISSUE TITLE
Support for  Tesla V100, running SM 7.0

### ISSUE THREAD

**Issue by rajserc** [amzn/amazon-dsstne#148]
Getting Error: invalid device function launching kernel kScaleAndBias_kernel 

Looks like only following is supported

enum SM_VERSION
    {
        SM_3X,
        SM_5X,
        SM_6X,
    };

What can be done to workaround this issue ?

**Comment by scottlegrand** [comment]
You can fix this in about 2 minutes by adding

"-gencode arch=compute_70,code=sm_70 "

to lines 13 and 17 of src/amazon/dsstne/Makefile.inc

We already ported to CUDA 9, the code is Volta-compatible, but CUDA 9 was
prerelease when we did so and this would break on CUDA 8.



On Dec 15, 2017 5:40 PM, "rajserc" <notifications@github.com> wrote:

Getting Error: invalid device function launching kernel kScaleAndBias_kernel

Looks like only following is supported

enum SM_VERSION
{
SM_3X,
SM_5X,
SM_6X,
};

What can be done to workaround this issue ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/amzn/amazon-dsstne/issues/148>, or mute the thread

**Comment by rajserc** [comment]
Thanks. BTW, i tried to build the dockerfile and jsoncpp dependancy is not in the dockerfile that causes the docker build fail.

Tried adding following, 
`# JsonCpp setup
RUN cd /tmp && \
    wget https://github.com/open-source-parsers/jsoncpp/archive/svn-import.tar.gz  && \
    tar xvfz svn-import.tar.gz &&  \
    cd jsoncpp-svn-import && \
    mkdir -p build/release && \
    cd build/release && \
    cmake -DCMAKE_BUILD_TYPE=release -DJSONCPP_LIB_BUILD_SHARED=OFF -G "Unix Makefiles" ../.. && \
    make -j 8 && \
    make install && rm -rf /tmp/*
`

getting
In file included from NNTypes.cpp:14:0:
NNTypes.h:25:31: fatal error: jsoncpp/json/json.h: No such file or directory
 #include <jsoncpp/json/json.h>

The file is in /usr/local/include/json/json.h

What should i change to build the image ?

**Comment by scottlegrand** [comment]
#include <json/json.h>

ought to do the trick...

**Comment by rajserc** [comment]
Got past that, but is there version dependency for jsoncpp or is it a linker issue not sure

getting 
NNNetwork.cpp: In function 'NNNetwork* LoadNeuralNetworkJSON(const string&, uint32_t, const std::vector<NNDataSetBase*>&)':
NNNetwork.cpp:2763:59: error: 'class Json::ValueIterator' has no member named 'name'
                 string name                         = itr.name();
                                                           ^
make[1]: Leaving directory `/opt/amazon/dsstne/src/amazon/dsstne/engine'
make[1]: *** [NNNetwork.o] Error 1
make: *** [lib/libdsstne.a] Error 2

**Comment by scottlegrand** [comment]
Are you on a boon to 16.04 or 14.04?

**Comment by rajserc** [comment]
According to dockerfile it's Ubuntu 14

**Comment by ashley915** [comment]
having the same problem. If you managed to fix it please help by sharing! Thx

**Comment by rajserc** [comment]
unfortunately not yet

**Comment by ashley915** [comment]
I'm not using docker. Will it still work without Docker?

**Comment by rgeorgej** [comment]
With docker you need to be in ubuntu 16.04  as there was some backward incompatible changes  made with JsonCPP

**Comment by scottlegrand** [comment]
Did this get resolved?  We have long since checked in Volta support for DSSTNE and it works on a Vanilla Ubuntu 16.04 installation.
